# Generated by Django 3.1.6 on 2021-04-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://fooding.joshuariverol.com/images/meal-pictures/default.png', max_length=500),
        ),
    ]
